### ISSUE TITLE
Why is the post content hook used?

### ISSUE THREAD

**Issue by cweiske** [dmitryd/typo3-robots#6]
What is the reason for using `contentPostProc-output` instead of "normal" TypoScript to set the meta data?

`contentPostProc-output` is run on cached pages, which increases page generation time on the server.

**Comment by dmitryd** [comment]
What unique numeric index do you propose to use?
What page object name should be used (I saw page, htmlsite, pageObj, etc)?

There is no reliable way to make it with TS. Also processing time increase is so minuscule that don't have to be taken into account.

**Comment by cweiske** [comment]
- I'd use the numeric index `223`. If there is a public extension that uses the same index, then it can be changed.
- Even if you saw different names for `page`, I'd still use the default `page` which is used in all(?) tutorials.

**Comment by dmitryd** [comment]
Almost all my extensions use simple principle: "install & it works". Your way does not guarantee that. So I will not do it your way :)

**Comment by cweiske** [comment]
It was just a question to understand your intentions.
